Lab7:
	gcc -o Lab7 Lab7.s

clean:
	rm Lab7_4

main:
	gcc -o main main.s
	
Lab7_2:
	gcc -o Lab7_2 Lab7_2.s

Lab7_3:
	gcc -o Lab7_3 Lab7_3.s
	
Lab7_4: 
	gcc -o Lab7_4 Lab7_4.s
	
Lab7_5:
	gcc -o Lab7_5 Lab7_5.s
	
Lab7_6:
	gcc -o Lab7_6 Lab7_6.s
	
strat:
	make Lab7_5
